version: '3.8'

services:
  selenium:
    container_name: rg-selenium-container-2025
    image: selenium/standalone-firefox:latest
    ports:
      - "4444:4444"
    shm_size: 2g  # Prevent crashes due to low shared memory
